use_frameworks!

platform :ios, '9.0'

target 'YLFindSymbol_Example' do
  pod 'YLFindSymbol', :path => '../'

  target 'YLFindSymbol_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
