#use_frameworks!


inhibit_all_warnings!
install! 'cocoapods',:generate_multiple_pod_projects => true

platform :ios, '10.0'

target 'YLFindSymbol_Example' do
  pod 'YLFindSymbol', :path => '../'

  target 'YLFindSymbol_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
